### ISSUE TITLE
Some layouts don't appear in MacOS

### ISSUE THREAD

**Issue by dylanhand** [divvun/kbdgen#8]
The fix for #4 introduced an issue that may cause the `<actions>...</actions>` tag to be removed incorrectly, which results in the layout not appearing on MacOS after being installed.

This affects, for example, the mhr (Eastern & Meadow Mari) keyboard as reported by @rueter (see #4).

The problem affects keyboard layouts that have `actions` on some but not all layers.

**Comment by dylanhand** [comment]
@snomos 

I've just merged #7 which should fix this.

Can you re-generate the keyboards mentioned in #4 so we can confirm it's fixed them? Especially mdf and mhr.

**Comment by snomos** [comment]
@dylanhand I will regenerate the mentioned keyboards.

**Comment by snomos** [comment]
@dylanhand @rueter others: The keyboards have been regenerated, and should be available for update/installation via Divvun Manager.

@rueter the `udm` keyboard does not contain any desktop layouts, it is clearly a very early draft for a mobile keyboard. There's definitely work ahead 😊

**Comment by snomos** [comment]
Seems to be fixed, all layers visible as far as I can see. @dylanhand how can one test that a layer is not appearing?

**Comment by dylanhand** [comment]
@snomos the way to test is to ensure the keyboard appears as an option in System Settings on MacOS. The `.keylayout` XML was malformed in some cases before the latest fix, so some keyboards, like `mhr`, were not possible to be added. 

@rueter listed others keyboards that were affected in #4:
> The keyboards for mhr (Meadow & Eastern Mari), mrj (Hill Mari aka Western Mari), myv (Erzya), mdf (Moksha), kpv (Komi-Zyrian), yrk (Nenets), did not show up as possible keyboards to install after they had been downloaded using Divvun Manager.

**Comment by snomos** [comment]
> @rueter listed others keyboards that were affected in https://github.com/divvun/kbdgen/issues/4:

His latest comments were:

> The mrj (Hill Mari aka Western Mari) keyboard is only partial. It contains none of the extras required for mrj, so we will have to work on that.

Ie not an issue with installation. Is working wrt this bug.

> The mhr (Eastern & Meadow Mari) keyboard does not appear on my Ventura as a selectable, even after down loading it.

Just tested after I triggered a rebuild, and it works now, in the sense that it shows up in system prefs and can be activated.

> The udm keyboard, has a Saami flag and is, in fact, a Latin letter content. More work for us;)

As for `mrd`, it shows up and can be activated, but needs more work. Ie fixed re this bug.

Everything seems to be fine regarding this bug, thus closing.
